### PR TITLE
Initial draft of stateless dns server

### PR DESCRIPTION
**Pull request by jonasfj**
@gregarndt, have a look at tell me if this is crazy enough :)

No need to read the diff it's pretty unreadable.. just look at the readme of the branch...
And maybe `index.js`, but it should be pretty easy to make hostnames for a public ip given that you have the shared secret... Yeah, another secret for docker-worker .)

### CODE REVIEW

**Comment by jonasfj** [comment]
@gregarndt, if you think is sufficiently crazy I'll build the image and update the dns server we have running on tutum.co.
Then this would work 10 min later or so :)

**Comment by jonasfj** [comment]
oh, and we can publish this module to npm, so we can import the `createHostname` function :)

**Comment by gregarndt** [comment]
I like all the levels of crazy, ship it!

**Comment by jonasfj** [comment]
Will do... but probably after I ship some other stuff :)

**Pull request merged**
